// Builds config.yaml from config/networks.json (the single source of addresses) and
// copies compiled ABIs. Refuses to emit a config for an environment with no deployment.
import { readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../..");
const env = process.env.IMPREST_ENV ?? "testnet";
const net = JSON.parse(readFileSync(resolve(root, "config/networks.json"), "utf8"))[env];
const out = (n) => JSON.parse(readFileSync(resolve(root, `contracts/out/${n}.sol/${n}.json`), "utf8")).abi;
for (const n of ["Desk", "DeskFactory", "ImprestPool"]) writeFileSync(resolve(here, `../abis/${n}.json`), JSON.stringify(out(n), null, 1));
copyFileSync(resolve(root, "contracts/perpl-artifacts/Exchange.abi.json"), resolve(here, "../abis/PerplExchange.json"));

const dry = process.argv.includes("--example");
if (!dry && (!net.imprest.pool || !net.imprest.factory || net.imprest.deployBlock == null)) {
  console.error(`No Imprest deployment recorded for ${env} in config/networks.json; run with --example to emit a template.`);
  process.exit(1);
}
const addr = (a) => a ?? "0x0000000000000000000000000000000000000000";
const yaml = `# GENERATED by scripts/gen-config.mjs from config/networks.json (${env}). Do not edit.
# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: imprest-indexer
description: Imprest desks, pool and Perpl venue events on ${net.label}
field_selection:
  transaction_fields:
    - hash
contracts:
  - name: DeskFactory
    abi_file_path: abis/DeskFactory.json
    events:
      - event: DeskOpened
      - event: CohortAdded
  - name: Desk
    abi_file_path: abis/Desk.json
    events:
      - event: DeskActivated
      - event: TradeExecuted
      - event: Graduated
      - event: Claimed
      - event: FeesAccrued
      - event: EnforcementStarted
      - event: EnforceCloseFailed
      - event: PartialClose
      - event: SettlementPending
      - event: Settled
  - name: ImprestPool
    abi_file_path: abis/ImprestPool.json
    events:
      - event: DeskFunded
      - event: DeskSettled
      - event: IncomeReceived
      - event: ExposureRecorded
      - event: Deposit
      - event: Withdraw
  - name: PerplExchange
    abi_file_path: abis/PerplExchange.json
    events:
      - event: PositionLiquidated
chains:
  - id: ${net.chainId}
    start_block: ${net.imprest.deployBlock ?? 0}
    rpc:
      - url: ${net.rpcUrls[0]}
        for: fallback
    contracts:
      - name: DeskFactory
        address: ${addr(net.imprest.factory)}
      - name: ImprestPool
        address: ${addr(net.imprest.pool)}
      - name: Desk
      - name: PerplExchange
        address: ${addr(net.perpl.exchange)}
`;
writeFileSync(resolve(here, "../config.yaml"), yaml);
console.log(`config.yaml written for ${env}${dry ? " (example addresses)" : ""}`);
