// Exports ABIs from Foundry build output (contracts/out) and the vendored Perpl ABI into
// packages/core/src/abi/generated.ts, so every TypeScript consumer uses compiled truth.
import { readFileSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const out = (p) => JSON.parse(readFileSync(resolve(root, "contracts/out", p), "utf8"));
const contracts = {
  deskAbi: out("Desk.sol/Desk.json").abi,
  imprestPoolAbi: out("ImprestPool.sol/ImprestPool.json").abi,
  deskFactoryAbi: out("DeskFactory.sol/DeskFactory.json").abi,
  imprestErrorsAbi: out("ImprestTypes.sol/ImprestErrors.json").abi,
};
const perplFull = JSON.parse(readFileSync(resolve(root, "contracts/perpl-artifacts/Exchange.abi.json"), "utf8"));
const perplErrors = JSON.parse(readFileSync(resolve(root, "contracts/perpl-artifacts/Errors.abi.json"), "utf8"));
const keep = new Set([
  "getAccountByAddr", "getPosition", "getPerpetualInfo", "getMinAccountOpenCNS", "getExchangeInfo",
  "whitelistingEnabled", "getContractVersion", "isHalted", "getTakerFee", "getWithdrawAllowanceData",
  "PositionOpened", "PositionOpenedV2", "PositionClosed", "PositionIncreased", "PositionIncreasedV2",
  "PositionDecreased", "PositionLiquidated", "TakerOrderFilled", "TakerOrderFilledV2", "MarkUpdated",
  "AccountCreated", "CollateralDeposit", "CollateralWithdrawal", "OrderRequest", "OrderRequestV2",
]);
contracts.perplExchangeAbi = [...perplFull.filter((x) => keep.has(x.name)), ...perplErrors];

const erc20Abi = [
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "a", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "o", type: "address" }, { name: "s", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "s", type: "address" }, { name: "v", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
];
contracts.erc20Abi = erc20Abi;

let src = "// GENERATED by scripts/export-abis.mjs from contracts/out and contracts/perpl-artifacts. Do not edit.\n";
const hashes = {};
for (const [name, abi] of Object.entries(contracts)) {
  const json = JSON.stringify(abi);
  hashes[name] = createHash("sha256").update(json).digest("hex");
  src += `export const ${name} = ${json} as const;\n`;
}
src += `export const abiHashes = ${JSON.stringify(hashes, null, 2)} as const;\n`;
writeFileSync(resolve(root, "packages/core/src/abi/generated.ts"), src);
console.log("ABIs exported:", Object.keys(contracts).join(", "));
